[project]
name = "ke"
version = "0.1.0"
description = "Knowledge Engine"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "diskcache>=5.6.3",
    "crawl4ai>=0.3.7",
    "openrouter>=0.1.3",
]
